Akki-on-Rails/boxtag

- Gemfile.lock
- app/models/box.rb
- app/models/collection.rb
- app/models/item.rb
- app/models/user.rb
- app/models/user_collection.rb
- db/migrate/20220813090039_create_user_collections.rb
- db/migrate/20220813090206_create_collections.rb
- db/migrate/20220813090241_create_boxes.rb
- db/migrate/20220813090319_create_items.rb
- test/models/box_test.rb
- test/models/collection_test.rb
- test/models/item_test.rb
- test/models/user_collection_test.rb
I generated the core models and added associations
> added core models

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
Added colors and google fonts to config/_colors.scss /_fonts_scss
> adding colours and font as css variables

- app/models/box.rb
- app/models/collection.rb
- app/models/item.rb
- app/models/user.rb
- app/models/user_collection.rb
we've added the associations and validations for all models.
> created validations and associations

- db/schema.rb
- db/seeds.rb
> add some seeds

- app/controllers/collections_controller.rb
- test/controllers/collections_controller_test.rb
created the collection controller.
Also created methods for new, create, index, show and delete
> Boxtag collection controller

- app/assets/stylesheets/config/_colors.scss
- app/views/shared/_navbar.html.erb
I removed the brand, aligned right and added appropriate links (that will need updating with correct paths later)
> updated menu link

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_footer-navigation.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/card.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/pages/home.html.erb
Started "designing" the Collections and Boxes
added two buttons (button and button-main)
> adding components buttons, boxes, collections

- app/controllers/boxes_controller.rb
- app/views/boxes/index.html.erb
- app/views/boxes/show.html.erb
just add index show and delete method in box controller
> add index show and destroy method

- app/controllers/collections_controller.rb
- app/views/boxes/show.html.erb
- app/views/collections/edit.html.erb
add edit and update method and edit.html page
> add collection edit and update method

- app/assets/stylesheets/components/_button.scss
- app/controllers/pages_controller.rb
- app/views/pages/search.html.erb
- app/views/shared/_footer-navigation.html.erb
- app/views/shared/_navbar.html.erb
connected everything and created the view to display results
> Boxtag search

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
I cam across a bug in my original code and updated how the collections are retrieved in the controller
> Dashboard update

- app/controllers/user_collection_controller.rb
- db/seeds.rb
- test/controllers/user_collection_controller_test.rb
just i push new and create method.
> add new and create method

- app/controllers/items_controller.rb
did some refactoring on the item controller
> refactoring of items controller

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_avatar.scss
- app/controllers/application_controller.rb
- app/views/collections/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/pages/home.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20220820115846_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
Set up cloudinary 
set up active storage 
added upload photo to new and edit user 
added fallback if no photo is uploaded  
added styling for avatar-pic and the fallback 
added avatar and fallback to collections 
please check if .env exists and if it's in the gitignore 
We also need to make some changes when push to heroku. 
and also migrate
> Cloudinary / active storage 

- config/environments/production.rb
I set up SSL option on Heroku and added forcing_ssl to the app.
> SSL is now set and available for the app

- app/controllers/pages_controller.rb
Found the error in our search feature. Finally works!
> correcting error in pages controller for search method

- app/assets/stylesheets/pages/_home.scss
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
Updating the frontend
- homepage 
- login 
- edit / new user 
- adding our buttons and fonts / colors 
- wrapped all views inside a container with some padding.
> adding container to views, clean up the layout

- app/views/pages/search.html.erb
I added a "back" button similar to the browser's so we can get back to where we came from.
> added "back" button to search page

- app/assets/stylesheets/components/_camera.scss
- app/assets/stylesheets/components/_footer-navigation.scss
- app/controllers/qrcodes_controller.rb
- app/views/qrcodes/show.html.erb
- app/views/shared/_footer-navigation.html.erb
sorry could not manage the camera in a correct format in the footer, i sent the code if somebody wants to try....
> camera button in navbar and barcode creation with heroku address

- app/assets/stylesheets/components/_footer-navigation.scss
- app/controllers/user_collection_controller.rb
- app/views/layouts/application.html.erb
I changed the application.html.erb to fix the position of the footer. It is now sticky and I added the rest of the content inside a div to make it occupy the rest of the screen
> Footer bug

- app/assets/stylesheets/components/_footer-navigation.scss
some more space under the footer
> footer 8px up

- app/assets/stylesheets/pages/_home.scss
just changed the mesh gradient a bit to have more contrast to the main button
> changed mesh gradient for more contrast to the main button

- app/controllers/basic_qr_codes_controller.rb
- app/javascript/packs/basic-qr-code-reader.js
- app/views/basic_qr_codes/index.html.erb
- app/views/shared/_footer-navigation.html.erb
- config/routes.rb
- package-lock.json
- package.json
- yarn.lock
qrcode scan is redirecting to the boxtag.me boxes
> Barcode scan inapp

- public/404.html
- public/422.html
- public/500.html
> little changes in the error messages

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_footer-navigation.scss
- app/views/basic_qr_codes/index.html.erb
- app/views/shared/_footer-navigation.html.erb
also commented some lines around the barcode scan out
> footer changed, one button less

- app/assets/stylesheets/pages/_index.scss
- app/views/devise/registrations/edit.html.erb
changed the standard link to black and underline
> updated the edit profile with some options, avatar image etc.

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_footer-navigation.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/config/_icons.scss
- app/views/boxes/show.html.erb
- app/views/collections/show.html.erb
- app/views/shared/_footer-navigation.html.erb
I changed the symbols in the footer navigation to google material symbols.
> Boxtag footer

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/config/_icons.scss
- app/views/boxes/show.html.erb
- app/views/collections/show.html.erb
fixed the design for collection's show page/ changed the button for removing collaborators.
> Boxtag cosmetics

- app/views/qrcodes/show.html.erb
Used   window.print() instead of printFrame.src 
Added media Query for page. 
There is still some white space on the top and left side, but I think it's good.
Not every print can print the borders.
> fixing Qr code print page 

- app/javascript/packs/basic-qr-code-reader.js
- app/views/basic_qr_codes/index.html.erb
delayed the sound(450ms), added instructions for scan and filter for video input
> Delay sound

- app/views/collections/show.html.erb
- app/views/pages/home.html.erb
change the box count and items count in pages view and collection view page
> change the pluralize

- app/controllers/user_collections_controller.rb
- app/models/user_collection.rb
- app/views/user_collections/new.html.erb
I added an error message if a share is created with a non-existent user. Message is displayed as an alert
> added error messages for no user

- app/assets/stylesheets/components/_list.scss
- app/views/pages/home.html.erb
I added padding to the text content n the list items so the icons do not overlap.
> Text box size

- app/views/shared/_navbar.html.erb
> sticky navbar
